# Generated by Django 5.2.3 on 2025-06-12 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='دما (سانتی\u200cگراد)')),
                ('humidity', models.FloatField(verbose_name='رطوبت (درصد)')),
                ('light', models.FloatField(verbose_name='نور (لوکس)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داده گلخانه',
                'verbose_name_plural': 'داده\u200cهای گلخانه',
            },
        ),
    ]
