# Generated by Django 5.2.3 on 2025-06-12 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گلخانه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'گلخانه',
                'verbose_name_plural': 'گلخانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GreenhouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='دما (سانتی\u200cگراد)')),
                ('humidity', models.FloatField(verbose_name='رطوبت (درصد)')),
                ('light', models.FloatField(verbose_name='نور (لوکس)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='monitoring.greenhouse', verbose_name='گلخانه')),
            ],
            options={
                'verbose_name': 'داده گلخانه',
                'verbose_name_plural': 'داده\u200cهای گلخانه',
            },
        ),
    ]
